[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "fastembed>=0.8.1",
    "httpx>=0.28.1",
    "langchain>=1.4.2",
    "langchain-ollama>=1.1.0",
    "neo4j>=6.3.1",
    "openlit>=1.45.0",
    "pyjwt[crypto]>=2.10.0",
    "python-multipart>=0.0.32",
    "qdrant-client>=1.16.2",
    "uvicorn[standard]>=0.53.0",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
# Говорим uv_build, что искать пакеты нужно в корне папки backend, а не в src/
module-root = ""
package-names = ["config", "domain", "application", "infrastructure", "presentation", "tests"]
